' ============================================================
'  ImportReviewJSON_LO.bas
'  LibreOffice Basic (UNO API) — Linux/Windows/macOS
'  Tested with LibreOffice 24.2
'
'  Imports a review JSON file (generated by mhtml-cleaner -R)
'  into the "Remarks" sheet of the current spreadsheet.
'
'  Installation:
'    Tools -> Macros -> Edit Macros...
'    Paste this module under "My Macros" or the document's
'    macro library, then close the editor.
'
'  Usage: Tools -> Macros -> Run Macro -> ImportReviewJSON
'
'  LO Basic constraints applied throughout:
'    - All Dim at top of function (no Dim inside loops or blocks)
'    - No For-loop counter modified inside loop (use Do While)
'    - No Chr() in Case expressions (use a local DQ variable instead)
'    - No Private Const for strings (not supported)
'    - No String() return type (use Variant)
'    - No reserved word 'key' as parameter name (use sKey)
' ============================================================

Option Explicit

' Column indices — 0-based for UNO getCellByPosition(col, row)
Private Const COL_PEER    As Long = 0   ' A  Peer
Private Const COL_NO      As Long = 1   ' B  No.
Private Const COL_SECTION As Long = 3   ' D  Section
Private Const COL_REMARKS As Long = 4   ' E  Remarks
Private Const COL_TYPE    As Long = 5   ' F  Type
Private Const DATA_START  As Long = 15  ' First data row (row 14 is blank)

' ============================================================
'  Entry point
' ============================================================
Public Sub ImportReviewJSON()
    Dim fPath        As String
    Dim raw          As String
    Dim oDoc         As Object
    Dim oSheet       As Object
    Dim objects      As Variant
    Dim count        As Long
    Dim r            As Long
    Dim maxRow       As Long
    Dim cPeer        As String
    Dim cSect        As String
    Dim cRem         As String
    Dim nextNo       As Long
    Dim chk          As Long
    Dim cellNo       As Object
    Dim n            As Long
    Dim imported     As Long
    Dim i            As Long
    Dim obj          As String
    Dim sUser        As String
    Dim sArtifact    As String
    Dim sContext     As String
    Dim sText        As String
    Dim sDate        As String
    Dim oAnnotations As Object
    Dim oCellAddr    As New com.sun.star.table.CellAddress
    Dim sheetIndex   As Long
    Dim j            As Long
    Dim ann          As Object
    Dim annAddr      As Object
    Dim names        As Variant
    Dim k            As Long
    Dim nRows        As Long
    Dim oRows        As Object

    fPath = PickFile()
    If fPath = "" Then Exit Sub

    raw = ReadFile(fPath)
    If raw = "" Then
        MsgBox "File is empty or cannot be read:" & Chr(10) & fPath
        Exit Sub
    End If

    oDoc = ThisComponent
    If Not oDoc.Sheets.hasByName("Remarks") Then
        MsgBox "Sheet 'Remarks' not found in this document."
        Exit Sub
    End If
    oSheet = oDoc.Sheets.getByName("Remarks")

    ' Get 0-based sheet index for CellAddress
    names      = oDoc.Sheets.getElementNames()
    sheetIndex = 0
    For k = 0 To UBound(names)
        If names(k) = "Remarks" Then
            sheetIndex = k
            Exit For
        End If
    Next k

    objects = JsonSplitObjects(raw)
    count   = UBound(objects) - LBound(objects) + 1
    If count = 0 Or (count = 1 And objects(0) = "") Then
        MsgBox "No entries found in the JSON file."
        Exit Sub
    End If

    ' Find first empty data row (0-based index = DATA_START - 1)
    r      = DATA_START - 1
    maxRow = oSheet.getRows().getCount() - 1
    Do While r <= maxRow
        cPeer = Trim(oSheet.getCellByPosition(COL_PEER,    r).getString())
        cSect = Trim(oSheet.getCellByPosition(COL_SECTION, r).getString())
        cRem  = Trim(oSheet.getCellByPosition(COL_REMARKS, r).getString())
        If cPeer = "" And cSect = "" And cRem = "" Then Exit Do
        r = r + 1
    Loop

    ' Continue numbering from the last existing No.
    nextNo = 1
    For chk = DATA_START - 1 To r - 1
        cellNo = oSheet.getCellByPosition(COL_NO, chk)
        If cellNo.getType() = 1 Then
            n = CLng(cellNo.getValue())
            If n >= nextNo Then nextNo = n + 1
        End If
    Next chk

    ' Insert blank rows at position r to avoid overwriting existing data
    nRows = 0
    For i = LBound(objects) To UBound(objects)
        If objects(i) <> "" Then nRows = nRows + 1
    Next i
    If nRows > 0 Then
        oRows = oSheet.getRows()
        oRows.insertByIndex(r, nRows)
    End If

    imported = 0
    For i = LBound(objects) To UBound(objects)
        obj = objects(i)
        If obj = "" Then GoTo NextObj

        sUser     = JsonGet(obj, "user")
        sArtifact = JsonGet(obj, "artifact")
        sContext  = JsonGet(obj, "context")
        sText     = JsonGet(obj, "text")
        sDate     = JsonGet(obj, "date")

        oSheet.getCellByPosition(COL_PEER,    r).setString(sUser)
        oSheet.getCellByPosition(COL_NO,      r).setValue(nextNo)
        oSheet.getCellByPosition(COL_SECTION, r).setString(sArtifact)
        oSheet.getCellByPosition(COL_REMARKS, r).setString(sText)
        oSheet.getCellByPosition(COL_TYPE,    r).setString(sContext)

        ' Store review date as cell annotation on Peer column
        If sDate <> "" Then
            oAnnotations     = oSheet.getAnnotations()
            oCellAddr.Sheet  = sheetIndex
            oCellAddr.Column = COL_PEER
            oCellAddr.Row    = r
            For j = oAnnotations.getCount() - 1 To 0 Step -1
                ann     = oAnnotations.getByIndex(j)
                annAddr = ann.getPosition()
                If annAddr.Column = COL_PEER And annAddr.Row = r Then
                    oAnnotations.removeByIndex(j)
                    Exit For
                End If
            Next j
            oAnnotations.insertNew(oCellAddr, sDate)
        End If

        r        = r + 1
        nextNo   = nextNo + 1
        imported = imported + 1

        NextObj:
    Next i

    MsgBox imported & " review(s) imported." & Chr(10) & "Source: " & fPath

End Sub

' ============================================================
'  File picker — UNO FileOpenDialog
' ============================================================
Private Function PickFile() As String
    Dim oDialog As Object
    Dim files   As Variant
    Dim url     As String

    oDialog = CreateUnoService("com.sun.star.ui.dialogs.FilePicker")
    oDialog.appendFilter("JSON files (*.json)", "*.json")
    oDialog.appendFilter("All files (*.*)", "*.*")
    oDialog.setCurrentFilter("JSON files (*.json)")

    If oDialog.execute() = 1 Then
        files    = oDialog.getSelectedFiles()
        url      = files(0)
        PickFile = ConvertFromURL(url)
    Else
        PickFile = ""
    End If
End Function

' ============================================================
'  Read entire text file into a string
' ============================================================
Private Function ReadFile(fPath As String) As String
    Dim fNum    As Integer
    Dim result  As String
    Dim oneLine As String

    fNum   = FreeFile()
    result = ""
    On Error GoTo ReadErr
    Open fPath For Input As #fNum
    Do While Not EOF(fNum)
        Line Input #fNum, oneLine
        result = result & oneLine & Chr(10)
    Loop
    Close #fNum
    ReadFile = result
    Exit Function
ReadErr:
    Close #fNum
    ReadFile = ""
End Function

' ============================================================
'  JsonSplitObjects
'  Splits "[{...},{...}]" into a Variant array of object strings.
'
'  DQ is a local variable holding Chr(34) — the double-quote char.
'  Using a variable (not Chr() function) makes it valid in Case.
' ============================================================
Private Function JsonSplitObjects(jsonArray As String) As Variant
    Dim DQ       As String
    Dim col()    As String
    Dim colSz    As Long
    Dim depth    As Long
    Dim inStr    As Boolean
    Dim objStart As Long
    Dim i        As Long
    Dim c        As String
    Dim sLen     As Long

    DQ       = Chr(34)
    colSz    = 0
    depth    = 0
    inStr    = False
    objStart = 0
    sLen     = Len(jsonArray)
    ReDim col(0)

    i = 1
    Do While i <= sLen
        c = Mid(jsonArray, i, 1)

        If inStr Then
            If c = "\" Then
                i = i + 1        ' skip escaped character
            ElseIf c = DQ Then
                inStr = False
            End If
        Else
            Select Case c
                Case DQ
                    inStr = True
                Case "{"
                    depth = depth + 1
                    If depth = 1 Then objStart = i
                Case "}"
                    If depth > 0 Then
                        depth = depth - 1
                        If depth = 0 And objStart > 0 Then
                            ReDim Preserve col(colSz)
                            col(colSz) = Mid(jsonArray, objStart, i - objStart + 1)
                            colSz      = colSz + 1
                            objStart   = 0
                        End If
                    End If
            End Select
        End If

        i = i + 1
    Loop

    If colSz = 0 Then
        ReDim col(0)
        col(0) = ""
    End If
    JsonSplitObjects = col
End Function

' ============================================================
'  JsonGet
'  Extracts the string value of sKey from a flat JSON object.
'  Handles \" and \\ escape sequences inside values.
'
'  DQ is a local variable holding Chr(34) — valid in Case.
' ============================================================
Private Function JsonGet(jsonObj As String, sKey As String) As String
    Dim DQ        As String
    Dim searchFor As String
    Dim pos       As Long
    Dim ch        As String
    Dim esc       As String
    Dim result    As String
    Dim sLen      As Long

    DQ        = Chr(34)
    searchFor = DQ & sKey & DQ
    pos       = InStr(jsonObj, searchFor)
    If pos = 0 Then
        JsonGet = ""
        Exit Function
    End If

    ' Skip past the key token, then skip whitespace and colon
    pos  = pos + Len(searchFor)
    sLen = Len(jsonObj)
    Do While pos <= sLen
        ch = Mid(jsonObj, pos, 1)
        If ch <> " " And ch <> ":" And ch <> Chr(9) Then Exit Do
        pos = pos + 1
    Loop

    ' Expect opening quote
    If pos > sLen Or Mid(jsonObj, pos, 1) <> DQ Then
        JsonGet = ""
        Exit Function
    End If
    pos = pos + 1   ' move past opening quote

    ' Read until closing unescaped quote
    result = ""
    Do While pos <= sLen
        ch = Mid(jsonObj, pos, 1)
        If ch = "\" Then
            If pos + 1 <= sLen Then
                esc = Mid(jsonObj, pos + 1, 1)
                Select Case esc
                    Case DQ    : result = result & DQ
                    Case "\"   : result = result & "\"
                    Case "/"   : result = result & "/"
                    Case "n"   : result = result & " "
                    Case "r"   : result = result & ""
                    Case "t"   : result = result & " "
                    Case Else  : result = result & esc
                End Select
                pos = pos + 2
            Else
                pos = pos + 1
            End If
        ElseIf ch = DQ Then
            Exit Do
        Else
            result = result & ch
            pos    = pos + 1
        End If
    Loop

    JsonGet = result
End Function
