Attribute VB_Name = "ImportReviewJSON"
Option Explicit

' ============================================================
'  ImportReviewJSON.bas  —  Excel VBA (Office 2016+)
'  Imports a review JSON file (generated by mhtml-cleaner -R)
'  into the "Remarks" sheet.
'
'  Installation:
'    Alt+F11 -> File -> Import File -> select this .bas
'    OR: Alt+F11 -> Insert -> Module, then paste the content.
'
'  Usage: run ImportReviewJSON()
' ============================================================

Private Const DATA_START  As Long = 15  ' Row 14 stays blank below header

' Column indices (1-based, Excel Cells(row, col))
Private Const COL_PEER    As Long = 1   ' A  Peer
Private Const COL_NO      As Long = 2   ' B  No.
Private Const COL_SECTION As Long = 4   ' D  Section
Private Const COL_REMARKS As Long = 5   ' E  Remarks
Private Const COL_TYPE    As Long = 6   ' F  Type

' ============================================================
'  Entry point
' ============================================================
Public Sub ImportReviewJSON()

    ' 1. Select file
    '    GetOpenFilename returns False (Boolean) on cancel — use VarType check
    Dim vPath As Variant
    vPath = Application.GetOpenFilename( _
        FileFilter:="JSON files (*.json),*.json,All files (*.*),*.*", _
        Title:="Select review JSON file")
    If VarType(vPath) = vbBoolean Then Exit Sub   ' user cancelled
    Dim fPath As String: fPath = CStr(vPath)

    ' 2. Read file
    Dim fNum As Integer: fNum = FreeFile()
    Dim raw As String
    On Error GoTo OpenError
    Open fPath For Input As #fNum
    raw = Input(LOF(fNum), fNum)
    Close #fNum
    On Error GoTo 0

    ' 3. Locate sheet
    Dim ws As Worksheet
    On Error Resume Next
    Set ws = ThisWorkbook.Sheets("Remarks")
    On Error GoTo 0
    If ws Is Nothing Then
        MsgBox "Sheet 'Remarks' not found.", vbExclamation
        Exit Sub
    End If

    ' 4. Parse JSON array
    Dim objects As Collection
    Set objects = JsonSplitObjects(raw)
    If objects.Count = 0 Then
        MsgBox "No entries found in the JSON file.", vbInformation
        Exit Sub
    End If

    ' 5. Find first empty row (>= DATA_START)
    Dim r As Long: r = DATA_START
    Do While Trim(CStr(ws.Cells(r, COL_PEER).Value))    <> "" Or _
             Trim(CStr(ws.Cells(r, COL_SECTION).Value)) <> "" Or _
             Trim(CStr(ws.Cells(r, COL_REMARKS).Value)) <> ""
        r = r + 1
        If r > 1048576 Then MsgBox "Could not find empty row.": Exit Sub
    Loop

    ' 6. Continue numbering from last existing No.
    Dim nextNo As Long: nextNo = 1
    Dim chk As Long
    For chk = DATA_START To r - 1
        If IsNumeric(ws.Cells(chk, COL_NO).Value) Then
            If CLng(ws.Cells(chk, COL_NO).Value) >= nextNo Then
                nextNo = CLng(ws.Cells(chk, COL_NO).Value) + 1
            End If
        End If
    Next chk

    ' 7. Insert blank rows at position r to avoid overwriting existing data,
    '    then write into the freshly inserted rows.
    Dim nRows As Long: nRows = objects.Count
    ws.Rows(r & ":" & r + nRows - 1).Insert Shift:=xlDown, CopyOrigin:=xlFormatFromLeftOrAbove

    Dim imported As Long: imported = 0
    Dim obj As Variant
    For Each obj In objects
        Dim sUser     As String: sUser     = JsonGet(CStr(obj), "user")
        Dim sArtifact As String: sArtifact = JsonGet(CStr(obj), "artifact")
        Dim sContext  As String: sContext  = JsonGet(CStr(obj), "context")
        Dim sText     As String: sText     = JsonGet(CStr(obj), "text")
        Dim sDate     As String: sDate     = JsonGet(CStr(obj), "date")

        ws.Cells(r, COL_PEER).Value    = sUser
        ws.Cells(r, COL_NO).Value      = nextNo
        ws.Cells(r, COL_SECTION).Value = sArtifact
        ws.Cells(r, COL_REMARKS).Value = sText
        ws.Cells(r, COL_TYPE).Value    = sContext

        ' Store review date as cell comment on Peer column
        If sDate <> "" Then
            On Error Resume Next
            ws.Cells(r, COL_PEER).Comment.Delete
            On Error GoTo 0
            With ws.Cells(r, COL_PEER).AddComment(sDate)
                .Shape.Width  = 120
                .Shape.Height = 22
            End With
        End If

        r        = r + 1
        nextNo   = nextNo + 1
        imported = imported + 1
    Next obj

    MsgBox imported & " review(s) imported from:" & vbCrLf & fPath, vbInformation
    Exit Sub

OpenError:
    MsgBox "Cannot read file:" & vbCrLf & fPath, vbExclamation
End Sub

' ============================================================
'  JSON helpers  (no external library required)
' ============================================================

' Extract string value of `key` from a flat JSON object string.
' Uses VBScript.RegExp available in Office 2007+ on Windows.
Private Function JsonGet(jsonObj As String, key As String) As String
    Dim re  As Object
    Dim ms  As Object
    Dim v   As String
    Set re = CreateObject("VBScript.RegExp")
    re.Pattern    = """" & key & """\s*:\s*""((?:[^""\\]|\\.)*)"""
    re.IgnoreCase = False
    Set ms = re.Execute(jsonObj)
    If ms.Count = 0 Then JsonGet = "": Exit Function
    v = ms(0).SubMatches(0)
    v = Replace(v, "\""", Chr(34))
    v = Replace(v, "\\",  "\")
    v = Replace(v, "\/",  "/")
    v = Replace(v, "\n",  " ")
    v = Replace(v, "\r",  "")
    v = Replace(v, "\t",  " ")
    JsonGet = v
End Function

' Split JSON array string into a Collection of object strings.
Private Function JsonSplitObjects(jsonArray As String) As Collection
    Dim col      As New Collection
    Dim depth    As Long
    Dim inStr    As Boolean
    Dim i        As Long
    Dim c        As String
    Dim objStart As Long

    depth    = 0
    inStr    = False
    objStart = 0
    i        = 1

    Do While i <= Len(jsonArray)
        c = Mid(jsonArray, i, 1)
        If inStr Then
            If c = "\" Then
                i = i + 1       ' skip escaped character
            ElseIf c = """" Then
                inStr = False
            End If
        Else
            Select Case c
                Case """"
                    inStr = True
                Case "{"
                    depth = depth + 1
                    If depth = 1 Then objStart = i
                Case "}"
                    If depth > 0 Then
                        depth = depth - 1
                        If depth = 0 And objStart > 0 Then
                            col.Add Mid(jsonArray, objStart, i - objStart + 1)
                            objStart = 0
                        End If
                    End If
            End Select
        End If
        i = i + 1
    Loop

    Set JsonSplitObjects = col
End Function
