#!/usr/bin/env python3
"""
HTML Validator for files generated by mhtml-cleaner.
Checks that the output HTML is correct and self-contained.
"""

__version__ = '2.4'

import sys
import re
from pathlib import Path


class HTMLValidator:
    """Validates an HTML file produced by mhtml-cleaner"""

    def __init__(self, html_file: str, verbose: bool = True):
        self.html_file = html_file
        self.verbose = verbose
        self.html = None
        self.issues = []
        self.warnings = []
        self.passed = 0
        self.failed = 0

    def load(self) -> bool:
        try:
            with open(self.html_file, 'r', encoding='utf-8') as f:
                self.html = f.read()
            return True
        except Exception as e:
            print(f"❌ Cannot read {self.html_file}: {e}")
            return False

    def validate(self) -> bool:
        if not self.load():
            return False

        name = Path(self.html_file).name
        if self.verbose:
            print(f"\n{'='*60}")
            print(f"  HTML Validator — {name}")
            print(f"{'='*60}\n")

        tests = [
            ("HTML structure",          self._test_structure),
            ("No cid: references",      self._test_no_cid),
            ("No multipart structure",  self._test_no_multipart),
            ("Images injected",         self._test_images_injected),
            ("CSS injected",            self._test_css_injected),
            ("No localhost in src/href",self._test_no_localhost),
            ("No file:// URLs",         self._test_no_file_urls),
            ("Tags properly closed",    self._test_closed_tags),
            ("Anchors present",         self._test_anchors),
            ("Artifact links resolved", self._test_artifact_links),
            ("File size reasonable",    self._test_file_size),
        ]

        for test_name, test_func in tests:
            result = test_func()
            if result:
                self.passed += 1
                if self.verbose:
                    print(f"  ✅ {test_name}")
            else:
                self.failed += 1
                if self.verbose:
                    print(f"  ❌ {test_name}")

        self._print_summary()
        return self.failed == 0

    # ------------------------------------------------------------------ tests

    def _test_structure(self) -> bool:
        for marker in ('<!DOCTYPE html', '<!DOCTYPE HTML', '<html', '<head', '<body'):
            if marker.lower() in self.html.lower():
                if '<html' in self.html.lower() and '<head' in self.html.lower() and '<body' in self.html.lower():
                    return True
        missing = [t for t in ('DOCTYPE', '<html', '<head', '<body')
                   if t.lower().replace('doctype', '<!doctype html') not in self.html.lower()]
        checks = [
            ('<!DOCTYPE', 'DOCTYPE'),
            ('<html',     '<html>'),
            ('<head',     '<head>'),
            ('<body',     '<body>'),
        ]
        all_ok = True
        for marker, name in checks:
            if marker.lower() not in self.html.lower():
                self.issues.append(f"Missing {name}")
                all_ok = False
        return all_ok

    def _test_no_cid(self) -> bool:
        count = self.html.count('cid:')
        if count > 0:
            self.issues.append(f"Found {count} cid: references (MHTML artefact)")
            return False
        return True

    def _test_no_multipart(self) -> bool:
        if 'multipart' in self.html.lower():
            self.warnings.append("Found 'multipart' in HTML")
            return False
        return True

    def _test_images_injected(self) -> bool:
        data_urls = re.findall(r'data:image/\w+;base64,', self.html)
        if not data_urls:
            self.warnings.append("No base64 images found — file may have no embedded images")
            return True   # warning only, not a failure (some docs have no images)
        if self.verbose:
            print(f"       → {len(data_urls)} base64 image(s)")
        return True

    def _test_css_injected(self) -> bool:
        if '<style' not in self.html:
            self.issues.append("No <style> tag found")
            return False
        m = re.search(r'<style[^>]*>(.*?)</style>', self.html, re.DOTALL)
        if m:
            size_kb = len(m.group(1)) // 1024
            if size_kb < 10:
                self.warnings.append(f"CSS is very small ({size_kb} KB)")
            if self.verbose:
                print(f"       → {size_kb} KB of CSS injected")
        return True

    def _test_no_localhost(self) -> bool:
        remaining = re.findall(
            r'(?:src|href)\s*=\s*["\']([^"\']*localhost:\d+[^"\']*)["\']',
            self.html, re.IGNORECASE
        )
        if remaining:
            self.issues.append(f"Found {len(remaining)} localhost URL(s) still in src/href")
            for r in remaining[:3]:
                self.issues.append(f"  → {r[:100]}")
            return False
        return True

    def _test_no_file_urls(self) -> bool:
        if 'file://' in self.html:
            self.issues.append("Found file:// URL(s)")
            return False
        return True

    def _test_closed_tags(self) -> bool:
        all_ok = True
        for tag, name in (('html', 'HTML'), ('head', 'HEAD'), ('body', 'BODY')):
            opens  = len(re.findall(rf'<{tag}[\s>]', self.html, re.IGNORECASE))
            closes = len(re.findall(rf'</{tag}>', self.html, re.IGNORECASE))
            if opens != closes:
                self.issues.append(f"<{tag}>: {opens} open, {closes} close")
                all_ok = False
        return all_ok

    def _test_anchors(self) -> bool:
        # Numeric anchors from flatPage navigation
        numeric = re.findall(r'href="#\d+"', self.html)
        # Named anchors (section ids)
        named   = re.findall(r'id="\d+"', self.html)
        total   = len(numeric) + len(named)
        if total == 0:
            self.warnings.append("No numeric anchors found")
            return False
        if self.verbose:
            print(f"       → {len(numeric)} anchor link(s), {len(named)} anchor target(s)")
        return True

    def _test_artifact_links(self) -> bool:
        # Artifact anchors: href="#Doc.Type.Object" pattern
        artifact_links   = re.findall(r'href="#[A-Za-z]+\.[A-Za-z]+\.[A-Za-z][^"]*"', self.html)
        artifact_targets = re.findall(r'id="[A-Za-z]+\.[A-Za-z]+\.[A-Za-z][^"]*"', self.html)
        if self.verbose:
            print(f"       → {len(artifact_links)} artifact link(s), {len(artifact_targets)} artifact target(s)")
        # Not a failure if none exist — some docs may not have cross-references
        return True

    def _test_file_size(self) -> bool:
        size_mb = len(self.html) / (1024 * 1024)
        if size_mb > 50:
            self.warnings.append(f"File is very large ({size_mb:.1f} MB)")
        elif size_mb < 0.01:
            self.warnings.append(f"File is suspiciously small ({size_mb:.3f} MB)")
        if self.verbose:
            print(f"       → {size_mb:.2f} MB")
        return True

    # --------------------------------------------------------------- summary

    def _print_summary(self):
        print(f"\n{'='*60}")
        print(f"Result: {self.passed} passed / {self.failed} failed")
        print(f"{'='*60}")
        if self.issues:
            print(f"\nErrors ({len(self.issues)}):")
            for issue in self.issues:
                print(f"  ❌ {issue}")
        if self.warnings:
            print(f"\nWarnings ({len(self.warnings)}):")
            for w in self.warnings:
                print(f"  ⚠️  {w}")
        if self.failed == 0:
            print(f"\n✅ All tests passed — file is ready.")
        else:
            print(f"\n❌ {self.failed} test(s) failed.")


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description='HTML validator for files generated by mhtml-cleaner'
    )
    parser.add_argument('html_file', help='HTML file to validate')
    parser.add_argument('-q', '--quiet', action='store_true',
                        help='Quiet mode: print summary only')
    parser.add_argument('--version', action='version', version=f'test-html-validator {__version__}')
    args = parser.parse_args()

    if not Path(args.html_file).exists():
        print(f"❌ File not found: {args.html_file}")
        sys.exit(1)

    validator = HTMLValidator(args.html_file, verbose=not args.quiet)
    success = validator.validate()
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
